[package]
name = "ping"
version = "0.1.0"
authors = ["Nagamine, Hideaki <1995.hnagamin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pnet]
version = "0.34.0"
